//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nav() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Shared.Nav", typeof(Nav).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ManEx.
        /// </summary>
        public static string aboutManex {
            get {
                return ResourceManager.GetString("aboutManex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ManEx.
        /// </summary>
        public static string closeManex {
            get {
                return ResourceManager.GetString("closeManex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ManEx.
        /// </summary>
        public static string contactManex {
            get {
                return ResourceManager.GetString("contactManex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Administration.
        /// </summary>
        public static string groupAdminPages {
            get {
                return ResourceManager.GetString("groupAdminPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Group Roles.
        /// </summary>
        public static string hideRolesTool {
            get {
                return ResourceManager.GetString("hideRolesTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homeModule {
            get {
                return ResourceManager.GetString("homeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string kb {
            get {
                return ResourceManager.GetString("kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manex System Options.
        /// </summary>
        public static string mx {
            get {
                return ResourceManager.GetString("mx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string navigation {
            get {
                return ResourceManager.GetString("navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in.
        /// </summary>
        public static string notLoggedIn {
            get {
                return ResourceManager.GetString("notLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Module.
        /// </summary>
        public static string openModule {
            get {
                return ResourceManager.GetString("openModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string orderStatusModule {
            get {
                return ResourceManager.GetString("orderStatusModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string saveSearchCriteria {
            get {
                return ResourceManager.GetString("saveSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All.
        /// </summary>
        public static string searchAll {
            get {
                return ResourceManager.GetString("searchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string searchAll2 {
            get {
                return ResourceManager.GetString("searchAll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string searchMdls {
            get {
                return ResourceManager.GetString("searchMdls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/ID.
        /// </summary>
        public static string searchNm {
            get {
                return ResourceManager.GetString("searchNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string searchNmContacts {
            get {
                return ResourceManager.GetString("searchNmContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string searchNmContactsContactInfo {
            get {
                return ResourceManager.GetString("searchNmContactsContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string searchNmContactsCust {
            get {
                return ResourceManager.GetString("searchNmContactsCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string searchNmCust {
            get {
                return ResourceManager.GetString("searchNmCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Material.
        /// </summary>
        public static string searchNmCustBom {
            get {
                return ResourceManager.GetString("searchNmCustBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string searchNmCustContacts {
            get {
                return ResourceManager.GetString("searchNmCustContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string searchNmCustCustInfo {
            get {
                return ResourceManager.GetString("searchNmCustCustInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string searchNmCustInvoices {
            get {
                return ResourceManager.GetString("searchNmCustInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string searchNmCustOrderStatus {
            get {
                return ResourceManager.GetString("searchNmCustOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Slips.
        /// </summary>
        public static string searchNmCustPackingSlips {
            get {
                return ResourceManager.GetString("searchNmCustPackingSlips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFT.
        /// </summary>
        public static string searchNmCustSft {
            get {
                return ResourceManager.GetString("searchNmCustSft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep.
        /// </summary>
        public static string searchNmSalesRep {
            get {
                return ResourceManager.GetString("searchNmSalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string searchNmSalesRepInvoices {
            get {
                return ResourceManager.GetString("searchNmSalesRepInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string searchOth {
            get {
                return ResourceManager.GetString("searchOth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string searchOthSn {
            get {
                return ResourceManager.GetString("searchOthSn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFT.
        /// </summary>
        public static string searchOthSnSft {
            get {
                return ResourceManager.GetString("searchOthSnSft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string searchPn {
            get {
                return ResourceManager.GetString("searchPn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string searchPnCust {
            get {
                return ResourceManager.GetString("searchPnCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Material.
        /// </summary>
        public static string searchPnCustBom {
            get {
                return ResourceManager.GetString("searchPnCustBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing List.
        /// </summary>
        public static string searchPnCustPackingList {
            get {
                return ResourceManager.GetString("searchPnCustPackingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFT.
        /// </summary>
        public static string searchPnInt {
            get {
                return ResourceManager.GetString("searchPnInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string searchPnIntBom {
            get {
                return ResourceManager.GetString("searchPnIntBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string searchPnInternal {
            get {
                return ResourceManager.GetString("searchPnInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Slip.
        /// </summary>
        public static string searchPnIntPackingSlip {
            get {
                return ResourceManager.GetString("searchPnIntPackingSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier/Manufacturer.
        /// </summary>
        public static string searchPnSup {
            get {
                return ResourceManager.GetString("searchPnSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string searchPnSupBom {
            get {
                return ResourceManager.GetString("searchPnSupBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Number.
        /// </summary>
        public static string searchRn {
            get {
                return ResourceManager.GetString("searchRn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string searchRnOther {
            get {
                return ResourceManager.GetString("searchRnOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string searchRnOtherInvoice {
            get {
                return ResourceManager.GetString("searchRnOtherInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Slip.
        /// </summary>
        public static string searchRnOtherPckingSlip {
            get {
                return ResourceManager.GetString("searchRnOtherPckingSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        public static string searchRnSo {
            get {
                return ResourceManager.GetString("searchRnSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string searchRnSoPl {
            get {
                return ResourceManager.GetString("searchRnSoPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFT.
        /// </summary>
        public static string searchRnSoSft {
            get {
                return ResourceManager.GetString("searchRnSoSft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO.
        /// </summary>
        public static string searchRnWo {
            get {
                return ResourceManager.GetString("searchRnWo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFT.
        /// </summary>
        public static string searchRnWoSft {
            get {
                return ResourceManager.GetString("searchRnWoSft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortages.
        /// </summary>
        public static string searchRnWoShortages {
            get {
                return ResourceManager.GetString("searchRnWoShortages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string searchRpts {
            get {
                return ResourceManager.GetString("searchRpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string setup {
            get {
                return ResourceManager.GetString("setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Group Roles.
        /// </summary>
        public static string showRolesTool {
            get {
                return ResourceManager.GetString("showRolesTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string tickets {
            get {
                return ResourceManager.GetString("tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        public static string updateCheck {
            get {
                return ResourceManager.GetString("updateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string userAdminPages {
            get {
                return ResourceManager.GetString("userAdminPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Forum.
        /// </summary>
        public static string userForum {
            get {
                return ResourceManager.GetString("userForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Training.
        /// </summary>
        public static string videoTraining {
            get {
                return ResourceManager.GetString("videoTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome: .
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
