//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Shared.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string _internal {
            get {
                return ResourceManager.GetString("_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Customer.
        /// </summary>
        public static string assignedCustomer {
            get {
                return ResourceManager.GetString("assignedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Supplier.
        /// </summary>
        public static string assignedSupplier {
            get {
                return ResourceManager.GetString("assignedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Material.
        /// </summary>
        public static string billOfMaterial {
            get {
                return ResourceManager.GetString("billOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Search Criteria.
        /// </summary>
        public static string invalidSearchCriteria {
            get {
                return ResourceManager.GetString("invalidSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string licenseType {
            get {
                return ResourceManager.GetString("licenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string modules {
            get {
                return ResourceManager.GetString("modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Id.
        /// </summary>
        public static string nameId {
            get {
                return ResourceManager.GetString("nameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.  .
        /// </summary>
        public static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string orderStatus {
            get {
                return ResourceManager.GetString("orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Id.
        /// </summary>
        public static string recordId {
            get {
                return ResourceManager.GetString("recordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Number.
        /// </summary>
        public static string recordNumber {
            get {
                return ResourceManager.GetString("recordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep.
        /// </summary>
        public static string salesRep {
            get {
                return ResourceManager.GetString("salesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search All.
        /// </summary>
        public static string searchAll {
            get {
                return ResourceManager.GetString("searchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string serialNum {
            get {
                return ResourceManager.GetString("serialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier / Manufacturer.
        /// </summary>
        public static string supplierManufacturer {
            get {
                return ResourceManager.GetString("supplierManufacturer", resourceCulture);
            }
        }
    }
}
