//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Order {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Order.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Ord.
        /// </summary>
        public static string backOrd {
            get {
                return ResourceManager.GetString("backOrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed in the last 30 days.
        /// </summary>
        public static string closed30 {
            get {
                return ResourceManager.GetString("closed30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed in the last 90 days.
        /// </summary>
        public static string closed90 {
            get {
                return ResourceManager.GetString("closed90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string dueDate {
            get {
                return ResourceManager.GetString("dueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string invoiceDate {
            get {
                return ResourceManager.GetString("invoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string invoicNumber {
            get {
                return ResourceManager.GetString("invoicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ord Date.
        /// </summary>
        public static string ordDate {
            get {
                return ResourceManager.GetString("ordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string orderStatus {
            get {
                return ResourceManager.GetString("orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ord Qty.
        /// </summary>
        public static string ordQty {
            get {
                return ResourceManager.GetString("ordQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing List.
        /// </summary>
        public static string packingList {
            get {
                return ResourceManager.GetString("packingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string partNumber {
            get {
                return ResourceManager.GetString("partNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purch Order.
        /// </summary>
        public static string purchOrder {
            get {
                return ResourceManager.GetString("purchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relsd.
        /// </summary>
        public static string relsd {
            get {
                return ResourceManager.GetString("relsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string salesOrder {
            get {
                return ResourceManager.GetString("salesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Customer.
        /// </summary>
        public static string selectedCust {
            get {
                return ResourceManager.GetString("selectedCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Date.
        /// </summary>
        public static string shipDate {
            get {
                return ResourceManager.GetString("shipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Qty.
        /// </summary>
        public static string shipQty {
            get {
                return ResourceManager.GetString("shipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Via.
        /// </summary>
        public static string shipVia {
            get {
                return ResourceManager.GetString("shipVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order Status.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        public static string trackingNumber {
            get {
                return ResourceManager.GetString("trackingNumber", resourceCulture);
            }
        }
    }
}
