//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Super User.
        /// </summary>
        public static string acctSuperUser {
            get {
                return ResourceManager.GetString("acctSuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account was succesfully created.
        /// </summary>
        public static string addConfirmation {
            get {
                return ResourceManager.GetString("addConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Button.
        /// </summary>
        public static string addUserDesc {
            get {
                return ResourceManager.GetString("addUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Admin User.
        /// </summary>
        public static string adminUser {
            get {
                return ResourceManager.GetString("adminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Company.
        /// </summary>
        public static string assignedCompany {
            get {
                return ResourceManager.GetString("assignedCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string authError {
            get {
                return ResourceManager.GetString("authError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Customers.
        /// </summary>
        public static string availCustomers {
            get {
                return ResourceManager.GetString("availCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Suppliers.
        /// </summary>
        public static string availSuppliers {
            get {
                return ResourceManager.GetString("availSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot change password.
        /// </summary>
        public static string cantChangePw {
            get {
                return ResourceManager.GetString("cantChangePw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseat All Sessions.
        /// </summary>
        public static string clearUserSeats {
            get {
                return ResourceManager.GetString("clearUserSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseat Button.
        /// </summary>
        public static string clearUserSeatsDesc {
            get {
                return ResourceManager.GetString("clearUserSeatsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to unseat the user.  Please refresh the page and try again.
        /// </summary>
        public static string clearUserSeatsError {
            get {
                return ResourceManager.GetString("clearUserSeatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unseated user from all sessions.
        /// </summary>
        public static string clearUserSeatsSuccess {
            get {
                return ResourceManager.GetString("clearUserSeatsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirmPw {
            get {
                return ResourceManager.GetString("confirmPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Another Account.
        /// </summary>
        public static string createAnother {
            get {
                return ResourceManager.GetString("createAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New User.
        /// </summary>
        public static string createNew {
            get {
                return ResourceManager.GetString("createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expiration interval (days).
        /// </summary>
        public static string dayExpirationInterval {
            get {
                return ResourceManager.GetString("dayExpirationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE:  When a user is created, the password is automatically saved as &quot;default&quot;.  When the user logs in for the first time, they will be asked to change their password..
        /// </summary>
        public static string defaultPwNotice {
            get {
                return ResourceManager.GetString("defaultPwNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this user.
        /// </summary>
        public static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user account?.
        /// </summary>
        public static string deleteUserConfirm {
            get {
                return ResourceManager.GetString("deleteUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Button.
        /// </summary>
        public static string deleteUserDesc {
            get {
                return ResourceManager.GetString("deleteUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted.
        /// </summary>
        public static string deleteUserSuccess {
            get {
                return ResourceManager.GetString("deleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for.
        /// </summary>
        public static string detailsFor {
            get {
                return ResourceManager.GetString("detailsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string dupEmail {
            get {
                return ResourceManager.GetString("dupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string dupUsrNm {
            get {
                return ResourceManager.GetString("dupUsrNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Button.
        /// </summary>
        public static string editButton {
            get {
                return ResourceManager.GetString("editButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved.
        /// </summary>
        public static string editConfirmation {
            get {
                return ResourceManager.GetString("editConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when trying to save changes. Please update the fields and try again..
        /// </summary>
        public static string editUnsuccessful {
            get {
                return ResourceManager.GetString("editUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempt.
        /// </summary>
        public static string exempt {
            get {
                return ResourceManager.GetString("exempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string external {
            get {
                return ResourceManager.GetString("external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string fullLicense {
            get {
                return ResourceManager.GetString("fullLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string groupName {
            get {
                return ResourceManager.GetString("groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT.
        /// </summary>
        public static string init {
            get {
                return ResourceManager.GetString("init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials.
        /// </summary>
        public static string initials {
            get {
                return ResourceManager.GetString("initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string invalidPw {
            get {
                return ResourceManager.GetString("invalidPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string invalieUn {
            get {
                return ResourceManager.GetString("invalieUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last log in.
        /// </summary>
        public static string lastLoginDate {
            get {
                return ResourceManager.GetString("lastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last time password was changed.
        /// </summary>
        public static string lastPwChangeDate {
            get {
                return ResourceManager.GetString("lastPwChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0 means no expiration).
        /// </summary>
        public static string leaveZeroForNoExpire {
            get {
                return ResourceManager.GetString("leaveZeroForNoExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string licenseType {
            get {
                return ResourceManager.GetString("licenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Changing the License Type will disconnect any open sessions for this user and they will have to re-authenticate.
        /// </summary>
        public static string licenseTypeChangeWarning {
            get {
                return ResourceManager.GetString("licenseTypeChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string licenseTypeCust {
            get {
                return ResourceManager.GetString("licenseTypeCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string licenseTypeFull {
            get {
                return ResourceManager.GetString("licenseTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string licenseTypeProduction {
            get {
                return ResourceManager.GetString("licenseTypeProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Only.
        /// </summary>
        public static string licenseTypeView {
            get {
                return ResourceManager.GetString("licenseTypeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string licenstTypeSupplier {
            get {
                return ResourceManager.GetString("licenstTypeSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expire interval (days).
        /// </summary>
        public static string passwordExpireInterval {
            get {
                return ResourceManager.GetString("passwordExpireInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 5 characters long..
        /// </summary>
        public static string passwordLength {
            get {
                return ResourceManager.GetString("passwordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string passwordNoMatch {
            get {
                return ResourceManager.GetString("passwordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Settings.
        /// </summary>
        public static string passwordSettings {
            get {
                return ResourceManager.GetString("passwordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string prodLicense {
            get {
                return ResourceManager.GetString("prodLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Super User.
        /// </summary>
        public static string prodSuperUser {
            get {
                return ResourceManager.GetString("prodSuperUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was added successfully.
        /// </summary>
        public static string saveConfirmation {
            get {
                return ResourceManager.GetString("saveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string saveUnsuccessful {
            get {
                return ResourceManager.GetString("saveUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the roles you would like this user to have.
        /// </summary>
        public static string selectRoles {
            get {
                return ResourceManager.GetString("selectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Status and Password.
        /// </summary>
        public static string statusPw {
            get {
                return ResourceManager.GetString("statusPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Users.
        /// </summary>
        public static string superUsers {
            get {
                return ResourceManager.GetString("superUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timeout (minutes).
        /// </summary>
        public static string timeoutLimit {
            get {
                return ResourceManager.GetString("timeoutLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string unknownErr {
            get {
                return ResourceManager.GetString("unknownErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string userAdmin {
            get {
                return ResourceManager.GetString("userAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is suspended.
        /// </summary>
        public static string userApproved {
            get {
                return ResourceManager.GetString("userApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username field is required.
        /// </summary>
        public static string usernameReq {
            get {
                return ResourceManager.GetString("usernameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset user password to default.
        /// </summary>
        public static string userPwChange {
            get {
                return ResourceManager.GetString("userPwChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string userType {
            get {
                return ResourceManager.GetString("userType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Roles.
        /// </summary>
        public static string viewRoles {
            get {
                return ResourceManager.GetString("viewRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Roles Button.
        /// </summary>
        public static string viewRolesDesc {
            get {
                return ResourceManager.GetString("viewRolesDesc", resourceCulture);
            }
        }
    }
}
